package org.sarmidev.kardano.crypto.derivation

import org.sarmidev.kardano.KardanoResult
import org.sarmidev.kardano.crypto.mnemonic.Mnemonic
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.fail

/**
 * Known-answer tests for [IcarusMasterKey.fromMnemonic] using the official CIP-3 (Icarus) test
 * vectors, copied verbatim from their source. No expected master key is generated by this SDK.
 *
 * Source: CIP-3 `Icarus.md` (CC-BY-4.0), repo `cardano-foundation/CIPs`, pinned commit
 * `a36e1ebca139ab4b31e12f0bf84bfb99481528bb`.
 *
 * [IcarusMasterKey] has no public byte accessor (ADR-0009 §7), so these tests reach the
 * derived bytes through [rootKeyBytesForTesting], a module-internal test-only accessor.
 */
class IcarusMasterKeyVectorsTest {

    private val recoveryPhrase =
        "eight country switch draw meat scout mystery blade tip drift useless good keep usage title"

    @Test
    fun fromMnemonic_noPassphrase_matchesCip3Vector1() {
        val expected = decodeHex(
            "c065afd2832cd8b087c4d9ab7011f481ee1e0721e78ea5dd609f3ab3f156d245d176bd8fd4ec60b47" +
                "31c3918a2a72a0226c0cd119ec35b47e4d55884667f552a23f7fdcd4a10c6cd2c7393ac61d877873" +
                "e248f417634aa3d812af327ffe9d620",
        )

        val master = deriveMaster(recoveryPhrase, passphrase = ByteArray(0))

        assertContentEquals(expected, master.rootKeyBytesForTesting())
    }

    @Test
    fun fromMnemonic_withFooPassphrase_matchesCip3Vector2() {
        val expected = decodeHex(
            "70531039904019351e1afb361cd1b312a4d0565d4ff9f8062d38acf4b15cce41d7b5738d9c893fee" +
                "a55512a3004acb0d222c35d3e3d5cde943a15a9824cbac59443cf67e589614076ba01e354b1a432" +
                "e0e6db3b59e37fc56b5fb0222970a010e",
        )

        // CIP-3 vector 2: passphrase "foo" as UTF-8 bytes.
        val master = deriveMaster(recoveryPhrase, passphrase = "foo".encodeToByteArray())

        assertContentEquals(expected, master.rootKeyBytesForTesting())
    }

    private fun deriveMaster(phrase: String, passphrase: ByteArray): IcarusMasterKey {
        val mnemonic = when (val result = Mnemonic.parse(phrase)) {
            is KardanoResult.Ok -> result.value
            is KardanoResult.Err -> fail("expected Ok but got Err(${result.error})")
        }
        return when (val result = IcarusMasterKey.fromMnemonic(mnemonic, passphrase)) {
            is KardanoResult.Ok -> result.value
            is KardanoResult.Err -> fail("expected Ok but got Err(${result.error})")
        }
    }

    private fun decodeHex(hex: String): ByteArray =
        ByteArray(hex.length / 2) { i ->
            hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
}
