package org.sarmidev.kardano.crypto

import org.sarmidev.kardano.KardanoResult
import org.sarmidev.kardano.address.Address
import org.sarmidev.kardano.encoding.hex.Hex
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * Known-answer tests for [Hashing] using only official, cited test vectors copied verbatim
 * from their sources. No expected digest is generated by any hashing library here.
 */
class HashingVectorsTest {

    private val hashing: Hashing = Hashing.default()

    @Test
    fun blake2b224_matchesCip19PaymentCredential() {
        // Source: CIP-19 test vectors (CC-BY-4.0), https://cips.cardano.org/cip/CIP-19
        // Input: the 32-byte Ed25519 verification key encoded as
        //   addr_vk1w0l2sr2zgfm26ztc6nl9xy8ghsk5sh6ldwemlpmp9xylzy4dtf7st80zhd
        // which bech32-decodes to the raw key bytes below (a decode, not a hash).
        val verificationKey =
            hex("73fea80d424276ad0978d4fe5310e8bc2d485f5f6bb3bf87612989f112ad5a7d")

        // Expected: the 28-byte payment credential (the blake2b-224 of that key per CIP-19),
        // taken from the full CIP-19 type-00 address below via :core Address.parse. The
        // credential is read structurally from the cited address, not produced by hashing.
        // For reference it is 9493315cd92eb5d8c4304e67b7e16ae36d61d34502694657811a2c8e.
        val address = expectOk(
            Address.parse(
                "addr1qx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3n0d3vll" +
                    "myqwsx5wktcd8cc3sq835lu7drv2xwl2wywfgse35a3x",
            ),
        )
        val expected = address.paymentCredential?.hashBytes()
            ?: fail("CIP-19 address unexpectedly had no payment credential")

        val digest = digestOf(hashing.blake2b224(verificationKey))

        assertEquals(HashDigest.SIZE_224, digest.size)
        assertTrue(
            expected.contentEquals(digest.toByteArray()),
            "blake2b224 did not match the CIP-19 payment credential",
        )
    }

    @Test
    fun blake2b256_emptyInput_matchesPlutusConformanceGolden() {
        // Source: IntersectMBO/plutus conformance goldens for the unkeyed blake2b_256 builtin
        // (Apache-2.0), commit 5e18824e2e0e30656c81d182e0ca512b75e7e57c, path prefix
        // plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/blake2b_256/
        // Vector blake2b_256-empty: input # (0 bytes).
        val input = ByteArray(0)
        val expected =
            hex("0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8")

        val digest = digestOf(hashing.blake2b256(input))

        assertEquals(HashDigest.SIZE_256, digest.size)
        assertTrue(
            expected.contentEquals(digest.toByteArray()),
            "blake2b256 of empty input did not match the Plutus conformance golden",
        )
    }

    @Test
    fun blake2b256_length25Input_matchesPlutusConformanceGolden() {
        // Source: IntersectMBO/plutus conformance goldens for the unkeyed blake2b_256 builtin
        // (Apache-2.0), commit 5e18824e2e0e30656c81d182e0ca512b75e7e57c, path prefix
        // plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/blake2b_256/
        // Vector blake2b_256-length-200: input #2e7ea84da4bc4d7cfb463e3f2c8647057afff3fbececa1d200 (25 bytes).
        val input = hex("2e7ea84da4bc4d7cfb463e3f2c8647057afff3fbececa1d200")
        val expected =
            hex("91c60f99b33303c02b39ed93b713e3915a180c3747f3b31e05727618ee401624")

        val digest = digestOf(hashing.blake2b256(input))

        assertEquals(HashDigest.SIZE_256, digest.size)
        assertTrue(
            expected.contentEquals(digest.toByteArray()),
            "blake2b256 of the 25-byte input did not match the Plutus conformance golden",
        )
    }

    private fun digestOf(result: KardanoResult<HashDigest, CryptoError>): HashDigest =
        when (result) {
            is KardanoResult.Ok -> result.value
            is KardanoResult.Err -> fail("expected Ok but got Err(${result.error})")
        }

    private fun <T, E> expectOk(result: KardanoResult<T, E>): T =
        when (result) {
            is KardanoResult.Ok -> result.value
            is KardanoResult.Err -> fail("expected Ok but got Err(${result.error})")
        }

    private fun hex(value: String): ByteArray =
        when (val result = Hex.decode(value)) {
            is KardanoResult.Ok -> result.value
            is KardanoResult.Err -> fail("invalid hex in test vector: ${result.error}")
        }
}
