package org.sarmidev.kardano.crypto.mnemonic

import org.sarmidev.kardano.KardanoResult
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.fail

/**
 * Known-answer tests for [Mnemonic.parse] using official, cited BIP-39 test vectors copied
 * verbatim from their source. No expected entropy is generated by this SDK; every value below
 * is transcribed from the cited fixture.
 *
 * Source: `trezor/python-mnemonic` `vectors.json` (MIT), pinned commit
 * `b57a5ad77a981e743f4167ab2f7927a55c1e82a8`, the `"english"` array. Only the
 * `(entropy hex, mnemonic)` columns are used: this block does not expose the BIP-39 seed
 * function or xprv serialization the other two columns exercise (ADR-0009 §2/§4).
 */
class MnemonicVectorsTest {

    @Test
    fun parse_12WordAllZeroEntropy_matchesTrezorVector() {
        assertParsesToEntropy(
            entropyHex = "00000000000000000000000000000000",
            phrase = "abandon abandon abandon abandon abandon abandon abandon abandon abandon " +
                "abandon abandon about",
        )
    }

    @Test
    fun parse_12WordAllOnesEntropy_matchesTrezorVector() {
        assertParsesToEntropy(
            entropyHex = "ffffffffffffffffffffffffffffffff",
            phrase = "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo wrong",
        )
    }

    @Test
    fun parse_12WordNonTrivialEntropy_matchesTrezorVector() {
        assertParsesToEntropy(
            entropyHex = "9e885d952ad362caeb4efe34a8e91bd2",
            phrase = "ozone drill grab fiber curtain grace pudding thank cruise elder eight picnic",
        )
    }

    @Test
    fun parse_18WordEntropy_matchesTrezorVector() {
        assertParsesToEntropy(
            entropyHex = "7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f7f",
            phrase = "legal winner thank year wave sausage worth useful legal winner thank year " +
                "wave sausage worth useful legal will",
        )
    }

    @Test
    fun parse_24WordEntropy_matchesTrezorVector() {
        assertParsesToEntropy(
            entropyHex = "066dca1a2bb7e8a1db2832148ce9933eea0f3ac9548d793112d9a95c9407efad",
            phrase = "all hour make first leader extend hole alien behind guard gospel lava path " +
                "output census museum junior mass reopen famous sing advance salt reform",
        )
    }

    private fun assertParsesToEntropy(entropyHex: String, phrase: String) {
        val mnemonic = when (val result = Mnemonic.parse(phrase)) {
            is KardanoResult.Ok -> result.value
            is KardanoResult.Err -> fail("expected Ok but got Err(${result.error})")
        }
        val expectedEntropy = decodeHex(entropyHex)
        assertEquals(phrase.split(" ").size, mnemonic.wordCount)
        assertContentEquals(expectedEntropy, mnemonic.entropyBytes())
    }

    private fun decodeHex(hex: String): ByteArray =
        ByteArray(hex.length / 2) { i ->
            hex.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
}
