package org.sarmidev.kardano.crypto.derivation

import org.sarmidev.kardano.KardanoResult
import org.sarmidev.kardano.crypto.mnemonic.Mnemonic
import org.sarmidev.kardano.encoding.bech32.Bech32
import uniffi.ed25519_bip32_wrapper.deriveBytes
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.fail

/**
 * Known-answer tests for [KeyDerivation.derivePrivate] and [KeyDerivation.publicKey] using the
 * official `IntersectMBO/cardano-addresses` Shelley golden test vectors, copied verbatim from
 * their source. No expected key is generated by this SDK.
 *
 * JVM host-run by design, not a style choice: `:crypto:testAndroidHostTest` runs on the host
 * JVM, not Android, so it cannot prove the native-backed derivation/projection backends work on
 * real Android runtime. That proof lives in `androidDeviceTest`'s `KeyDerivationDeviceTest`
 * (real on-device derivation, verified) — public-key projection specifically is not available
 * on Android at all (1.6c-follow-up gate result, ADR-0010): see
 * [KeyDerivationError.PublicKeyProjectionUnavailable].
 *
 * Source: `IntersectMBO/cardano-addresses` (Apache-2.0), path
 * `test/golden/addresses_5574d91d/golden`, pinned commit
 * `46d01319015275941f96126b2496453693f89538`.
 */
class KeyDerivationVectorsTest {

    private val mnemonic = listOf(
        "test", "walk", "nut", "penalty", "hip", "pave",
        "soap", "entry", "language", "right", "filter", "choice",
    )

    // CIP-5 bech32, copied verbatim from the pinned golden file (see class doc for source).
    private val rootXsk =
        "root_xsk1vzrzr76vqyqlavclduhawqvtae2pq8lk0424q7t8rzfjyhhp530zxv2fwq5a3pd4vdzqtu6s2zxdjh" +
            "ww8xg4qwcs7y5dqne5k7mz27p6rcaath83rl20nz0v9nwdaga9fkufjuucza8vmny8qpkzwstk5qh7s88m"
    private val acctXsk0 =
        "acct_xsk12phl7y4uv58mne08me5szrwly2gn6jasqmkvcrndq762q68p5302z24gdf365klhll2a5f357k7nc" +
            "4kpaq7j6agr5m22jq4jwlfv6l505h7dg64an4rdfk9f028nge0zcn508jw6m8lkdq36zc0v4h9xqsm27syf"
    private val acctXsk1 =
        "acct_xsk1ppjrs9d7yh6qzmzng34nyh5ysx4uzewz09ndyjudgep0x6lp530vzh0gmwrt53p3h55l8ect5cw95e" +
            "jpgj667eawewrcmrf2ajda4mzxlzpf2w63cwazlp9226pr4m6s35lawkmrqv8gf8ycl0ernjf69vyva4mc"
    private val addrXsk0 =
        "addr_xsk1hqf6v2lvhfn5mr3fe6g8ac6n8a3z6s0p24mg6kre8jadxulp530y07wjp2ml0zcz8gk0xc7zy96qp2" +
            "xxtr0arjq9038k9dhkw3k3cswawhs4fkjp00kwc4wd6fynyaz5zw8ssggs9974apatyhs4ltg4puw0nn7y"
    private val addrXsk1 =
        "addr_xsk1up30yhwmkujfkjd2rvy99z7qg7mdpqd8n7vehsyvfq20zulp530weme6mjk3yuqkynms9tr23wqcz" +
            "k94npvnp4r8l2vrq36l8vudk8lh4vfx72yymwg9n7sfe2pmu6ut6qjsgf4wkcser0wesc290w9ujykv4t85"
    private val addrXsk1442 =
        "addr_xsk14qtc6t6wfzk4jvdp0k8d9jp0xtlmhkh8el98nfnqwr5kqulp530vmhqefsml4rsntysxu057jecdq0" +
            "l3gmzs6c8nv5mvjn5aesmklzqepr3e4n4ca0p23tm57dwkw4ws46cz2mmdx3jnxtxy8zqyfekftvz8x0yj"

    // CIP-5 bech32 `addr_xvk` (extended verification key), copied verbatim from the pinned
    // golden file (see class doc for source).
    private val addrXvk0 =
        "addr_xvk1w0l2sr2zgfm26ztc6nl9xy8ghsk5sh6ldwemlpmp9xylzy4dtf7a6a0p2ndyz7lva32um5jfxf6" +
            "9gyu0pqs3q2tat6r6kf0pt7k32rcuhjq9l"
    private val addrXvk1 =
        "addr_xvk17cn2hzr7kh6qk5pyv0x09mz6wvgkwmhfuh24cjfqtx3kds956jsl02cjdu5gfkust8aqnj5rhe4" +
            "ch5p9qsn2ad3pjx7anps527uteygezrt4z"
    private val addrXvk1442 =
        "addr_xvk1l7vftt4ayg29thue83m2crav65wqzak2v9v7lryjnnphq88rsrr3jz8rnt8t367z4zhhfu6ava2" +
            "apt4sy4hk6dr9xvkvgwyqgnnvjkcyq26mk"

    @Test
    fun fromMnemonic_rootMatchesGoldenRootXsk() {
        val master = deriveMaster()

        assertContentEquals(decodeCip5(rootXsk), master.rootKeyBytesForTesting())
    }

    @Test
    fun derivePrivate_role0Index0_matchesGoldenAddrXsk0() {
        val master = deriveMaster()
        val path = okPath(Cip1852Path.of(account = 0, role = Cip1852Role.EXTERNAL, index = 0))

        val key = okKey(KeyDerivation.default().derivePrivate(master, path))

        assertContentEquals(decodeCip5(addrXsk0), key.xskBytesForTesting())
    }

    @Test
    fun derivePrivate_role0Index1_matchesGoldenAddrXsk1() {
        val master = deriveMaster()
        val path = okPath(Cip1852Path.of(account = 0, role = Cip1852Role.EXTERNAL, index = 1))

        val key = okKey(KeyDerivation.default().derivePrivate(master, path))

        assertContentEquals(decodeCip5(addrXsk1), key.xskBytesForTesting())
    }

    @Test
    fun derivePrivate_role0Index1442_matchesGoldenAddrXsk1442() {
        val master = deriveMaster()
        val path = okPath(Cip1852Path.of(account = 0, role = Cip1852Role.EXTERNAL, index = 1442))

        val key = okKey(KeyDerivation.default().derivePrivate(master, path))

        assertContentEquals(decodeCip5(addrXsk1442), key.xskBytesForTesting())
    }

    @Test
    fun publicKey_role0Index0_matchesGoldenAddrXvk0() {
        val master = deriveMaster()
        val path = okPath(Cip1852Path.of(account = 0, role = Cip1852Role.EXTERNAL, index = 0))
        val privateKey = okKey(KeyDerivation.default().derivePrivate(master, path))

        val publicKey = okPublicKey(KeyDerivation.default().publicKey(privateKey))

        assertContentEquals(decodeCip5(addrXvk0), publicKey.xvkBytesForTesting())
    }

    @Test
    fun publicKey_role0Index1_matchesGoldenAddrXvk1() {
        val master = deriveMaster()
        val path = okPath(Cip1852Path.of(account = 0, role = Cip1852Role.EXTERNAL, index = 1))
        val privateKey = okKey(KeyDerivation.default().derivePrivate(master, path))

        val publicKey = okPublicKey(KeyDerivation.default().publicKey(privateKey))

        assertContentEquals(decodeCip5(addrXvk1), publicKey.xvkBytesForTesting())
    }

    @Test
    fun publicKey_role0Index1442_matchesGoldenAddrXvk1442() {
        val master = deriveMaster()
        val path = okPath(Cip1852Path.of(account = 0, role = Cip1852Role.EXTERNAL, index = 1442))
        val privateKey = okKey(KeyDerivation.default().derivePrivate(master, path))

        val publicKey = okPublicKey(KeyDerivation.default().publicKey(privateKey))

        assertContentEquals(decodeCip5(addrXvk1442), publicKey.xvkBytesForTesting())
    }

    /**
     * Intermediate check for the `1852'/1815'/account'` prefix, one level short of a full
     * [Cip1852Path]. [KeyDerivation]'s public surface only derives a full 5-level path, so this
     * is a module-internal probe that steps the wrapper's `deriveBytes` directly over the
     * explicit two-prime-index prefix, not a public-API test.
     */
    @Test
    fun probeAccountPrefix0_matchesGoldenAcctXsk0() {
        val master = deriveMaster()

        val derived = deriveAccountPrefix(master, account = 0)

        assertContentEquals(decodeCip5(acctXsk0), derived)
    }

    @Test
    fun probeAccountPrefix1_matchesGoldenAcctXsk1() {
        val master = deriveMaster()

        val derived = deriveAccountPrefix(master, account = 1)

        assertContentEquals(decodeCip5(acctXsk1), derived)
    }

    private fun deriveAccountPrefix(master: IcarusMasterKey, account: Long): ByteArray {
        val root = master.rootExtendedKeyBytes()
        var sk = root.copyOfRange(0, 64)
        var chainCode = root.copyOfRange(64, 96)
        val prefixIndices = listOf(
            Cip1852Path.PURPOSE + Cip1852Path.PRIME_INDEX_OFFSET,
            Cip1852Path.COIN_TYPE + Cip1852Path.PRIME_INDEX_OFFSET,
            account + Cip1852Path.PRIME_INDEX_OFFSET,
        )
        for (index in prefixIndices) {
            val step = deriveBytes(sk, chainCode, index.toUInt())
            sk = step["secret_key"] ?: fail("missing secret_key in probe derivation step")
            chainCode = step["chain_code"] ?: fail("missing chain_code in probe derivation step")
        }
        return sk + chainCode
    }

    private fun deriveMaster(): IcarusMasterKey {
        val parsed = when (val result = Mnemonic.parse(mnemonic)) {
            is KardanoResult.Ok -> result.value
            is KardanoResult.Err -> fail("expected Ok but got Err(${result.error})")
        }
        return when (val result = IcarusMasterKey.fromMnemonic(parsed)) {
            is KardanoResult.Ok -> result.value
            is KardanoResult.Err -> fail("expected Ok but got Err(${result.error})")
        }
    }

    private fun okPath(
        result: KardanoResult<Cip1852Path, KeyDerivationError>,
    ): Cip1852Path = when (result) {
        is KardanoResult.Ok -> result.value
        is KardanoResult.Err -> fail("expected Ok but got Err(${result.error})")
    }

    private fun okKey(
        result: KardanoResult<ExtendedPrivateKey, KeyDerivationError>,
    ): ExtendedPrivateKey = when (result) {
        is KardanoResult.Ok -> result.value
        is KardanoResult.Err -> fail("expected Ok but got Err(${result.error})")
    }

    private fun okPublicKey(
        result: KardanoResult<ExtendedPublicKey, KeyDerivationError>,
    ): ExtendedPublicKey = when (result) {
        is KardanoResult.Ok -> result.value
        is KardanoResult.Err -> fail("expected Ok but got Err(${result.error})")
    }

    /** Decodes a CIP-5 bech32 key string to its raw bytes via [Bech32.decode] and [convert5BitTo8Bit]. */
    private fun decodeCip5(bech32: String): ByteArray {
        val decoded = when (val result = Bech32.decode(bech32)) {
            is KardanoResult.Ok -> result.value
            is KardanoResult.Err -> fail("expected Ok but got Err(${result.error})")
        }
        return convert5BitTo8Bit(decoded.toData5BitArray())
    }

    /**
     * Test-only 5-bit-to-8-bit conversion, mirroring BIP-173's `convertbits(data, 5, 8, False)`.
     *
     * This exists only here: `:core`'s equivalent (`Bech32.convertBits`) is `internal` to
     * `:core` and not visible from `:crypto` (ADR-0009 §Block 1.6c gate result). Bounded by
     * [MAX_5BIT_VALUES], checked before any output allocation, and rejects a non-canonical
     * (non-zero leftover bits) encoding rather than silently accepting it.
     *
     * @see <a href="https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki">BIP-173</a>
     */
    private fun convert5BitTo8Bit(data: ByteArray): ByteArray {
        require(data.size <= MAX_5BIT_VALUES) { "5-bit input too long for this test helper" }
        val outSize = data.size * 5 / 8
        val out = ByteArray(outSize)
        var acc = 0
        var bits = 0
        var oi = 0
        for (b in data) {
            val value = b.toInt() and 0xFF
            require(value in 0..31) { "not a 5-bit value: $value" }
            acc = ((acc shl 5) or value) and MAX_ACCUMULATOR
            bits += 5
            while (bits >= 8) {
                bits -= 8
                out[oi++] = ((acc ushr bits) and 0xFF).toByte()
            }
        }
        check(bits < 5 && ((acc shl (8 - bits)) and 0xFF) == 0) {
            "leftover bits are non-zero; not a canonical byte-aligned encoding"
        }
        return out
    }

    private companion object {
        /** Upper bound on 5-bit values [convert5BitTo8Bit] accepts, checked before allocation. */
        private const val MAX_5BIT_VALUES: Int = 256

        /** Mask matching BIP-173's `(1 << (fromBits + toBits - 1)) - 1` for fromBits=5, toBits=8. */
        private const val MAX_ACCUMULATOR: Int = 0xFFF
    }
}
