#!/usr/bin/env python3
"""Harvest a complete, committed coordinate -> license catalog from POMs.

This is a maintenance tool, not something CI runs. It exists to eliminate
`scripts/generate_legal_evidence.py`'s dependency on a pre-populated local
Gradle module cache (an independent review's 2026-08-24 finding: the
committed `docs/evidence/gradle_license_inventory.json` was only
reproducible on a machine whose `GRADLE_USER_HOME` already had every
coordinate's POM resolved -- a clean CI container has none of that, so the
"evidence freshness" check would fail there even though it passes locally).

For every Gradle-runtime coordinate across every module discovered from
`settings.gradle.kts` that is not already in the hand-curated
`scripts/license_catalog.GRADLE_LICENSE_CATALOG`, this script:

1. Reads the coordinate's own POM from the local Gradle module cache
   (`GRADLE_USER_HOME/caches/modules-2/files-2.1/...`) -- the same bytes
   `gradle_license_inventory()` would otherwise read live, but captured once
   here and committed so later runs (including a clean CI container) do not
   need that cache at all.
2. Requires exactly one `<license><name>` entry (this script refuses to
   silently pick one from a genuine multi-license POM; those need a
   reviewed election in `scripts/license_catalog.py` instead -- see its
   module docstring). As of 2026-08-24 zero of the harvested coordinates are
   multi-license; a future run finding one will raise loudly instead of
   dropping it.
3. Writes the exact `group:artifact:version -> {licenses, source}` mapping
   to `scripts/license_catalog_harvested.py`, sorted, deterministic, with a
   `harvested_date` per run (not per entry, to keep the file small) and a
   provenance comment explaining this is mechanically extracted POM data,
   not a manually reviewed election.

Re-run this after any lockfile change that introduces a coordinate not
already covered by `scripts/license_catalog.py` (curated or harvested);
`scripts/generate_legal_evidence.py` fails closed if any coordinate is
still unresolved after checking both catalogs and the live local cache.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import generate_legal_evidence as evidence  # noqa: E402
import license_catalog  # noqa: E402

HARVEST_DATE = "2026-08-24"
OUTPUT_PATH = Path(__file__).resolve().parent / "license_catalog_harvested.py"

HEADER = f'''"""Mechanically harvested Gradle coordinate -> license catalog.

Generated by `scripts/harvest_gradle_pom_licenses.py` on {HARVEST_DATE} from
the local Gradle module cache's own resolved POM `<licenses>` block for
every runtime coordinate not already covered by the hand-curated
`scripts/license_catalog.GRADLE_LICENSE_CATALOG`. This is factual,
mechanically extracted POM data (not a manual legal review, and never a
multi-license/election entry -- those stay in the curated catalog); it
exists so `scripts/generate_legal_evidence.py` never needs a pre-populated
local Gradle cache to reproduce `docs/evidence/gradle_license_inventory.json`
on a clean machine. Do not hand-edit; re-run the harvest script instead.
"""

from __future__ import annotations

from typing import Any

# group:artifact:version -> {{"licenses": [...], "source": None}}. Always
# single-license (see harvest script docstring); never carries an
# "election" key.
HARVESTED_POM_LICENSE_CATALOG: dict[str, dict[str, Any]] = {{
'''

FOOTER = "}\n"


def main() -> int:
    modules = evidence.discover_gradle_modules()
    gradle_report = evidence.gradle_dependency_inventory(modules)
    all_runtime_gavs: set[str] = set()
    for module_data in gradle_report["modules"].values():
        all_runtime_gavs.update(module_data["coordinates"]["runtime"])

    harvested: dict[str, list[str]] = {}
    still_unresolved: list[str] = []
    for gav in sorted(all_runtime_gavs):
        group, artifact, version = evidence.parse_gav(gav)
        if license_catalog.lookup(group, artifact, version) is not None:
            continue  # already covered by the curated catalog
        pom_path = evidence.find_local_pom(group, artifact, version)
        if pom_path is None:
            still_unresolved.append(gav)
            continue
        licenses = evidence.parse_pom_licenses(pom_path)
        if not licenses:
            still_unresolved.append(gav)
            continue
        if len(licenses) > 1:
            raise SystemExit(
                f"{gav}: POM lists {len(licenses)} licenses "
                f"({licenses!r}) -- this is a real multi-license coordinate "
                "that needs a reviewed election in scripts/license_catalog.py, "
                "not a mechanical harvest entry. Add it there and re-run."
            )
        harvested[gav] = licenses

    if still_unresolved:
        print(
            "WARNING: still unresolved after harvest attempt (no local POM, "
            f"or POM has no <licenses> block -- may need parent-POM "
            f"inheritance or a manual catalog entry): {sorted(still_unresolved)}",
            file=sys.stderr,
        )

    lines = [HEADER]
    for gav in sorted(harvested):
        licenses = harvested[gav]
        lines.append(f'    {gav!r}: {{"licenses": {licenses!r}, "source": None}},\n')
    lines.append(FOOTER)
    OUTPUT_PATH.write_text("".join(lines), encoding="utf-8")
    print(
        f"harvested {len(harvested)} coordinates to {OUTPUT_PATH.name} "
        f"({len(still_unresolved)} still unresolved)"
    )
    return 1 if still_unresolved else 0


if __name__ == "__main__":
    raise SystemExit(main())
